export {default as logo} from "./logo.svg"
export {default as hamb} from "./icon-hamburger.svg"
export {default as close} from "./icon-close.svg"
export {default as introDesk} from "./bg-intro-desktop.svg"
export {default as introMob} from "./bg-intro-mobile.svg"
export {default as hero} from "./image-mockups.png"
export {default as apiIcon} from "./icon-api.svg"
export {default as onlineIcon} from "./icon-online.svg"
export {default as budgetingIcon} from "./icon-budgeting.svg"
export {default as onboardingIcon} from "./icon-onboarding.svg"
export {default as firstArt} from "./image-currency.jpg"
export {default as secArt} from "./image-restaurant.jpg"
export {default as thirdArt} from "./image-plane.jpg"
export {default as fourOne} from "./image-confetti.jpg"
export {default as facebook} from "./icon-facebook.svg"
export {default as pinterest} from "./icon-pinterest.svg"
export {default as youtube} from "./icon-youtube.svg"
export {default as insta} from "./icon-instagram.svg"
export {default as twitter } from "./icon-twitter.svg"


