export {default as NavBar} from "./NavBar"
export {default as Hero} from "./Hero"
export {default as WhyUs} from "./WhyUs"
export {default as Latest} from "./LatestArt"
export {default as Footer} from "./Footer"